In [2]:
import numpy as np
from random import randint

In [5]:
def generate_sequence(length, n_features):
    return [randint(0, n_features - 1) for _ in range(length)]

In [10]:
seq = generate_sequence(5, 20)
seq

[7, 12, 14, 0, 7]

In [13]:
def one_hot_encode(sequence, n_features):
    encoding = list()
    for value in sequence:
        vector = [0 for _ in range(n_features)]
        vector[value] = 1
        encoding.append(vector)
    return np.array(encoding)

In [14]:
ohe = one_hot_encode(seq, 20)
ohe

array([[0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
def one_hot_decode(encoded_seq):
    return [np.argmax(vector) for vector in encoded_seq]

In [16]:
ohd = one_hot_decode(ohe)
ohd

[7, 12, 14, 0, 7]

In [18]:
features = 100
sequence = generate_sequence(25, features)
print(sequence)

[17, 55, 37, 48, 70, 14, 90, 8, 0, 65, 90, 7, 7, 64, 78, 7, 14, 25, 68, 75, 82, 34, 28, 65, 84]


In [19]:
encoded = one_hot_encode(sequence, features)
print(encoded)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [20]:
decoded = one_hot_decode(encoded)
print(decoded)

[17, 55, 37, 48, 70, 14, 90, 8, 0, 65, 90, 7, 7, 64, 78, 7, 14, 25, 68, 75, 82, 34, 28, 65, 84]


In [21]:
X = encoded.reshape(1, len(sequence), features)
print(X)
print(X.shape)

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
(1, 25, 100)


In [22]:
y = encoded[1, :]
print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [23]:
def generate_example(length, n_features, out_index):
    sequence = generate_sequence(length, n_features)
    encoded = one_hot_encode(sequence, n_features)
    X = encoded.reshape(1, length, n_features)
    y = encoded[out_index].reshape(1, -1)
    return X, y

In [24]:
X, y = generate_example(25, 100, 2)
print(X.shape)
print(y.shape)

(1, 25, 100)
(1, 100)


## Define the model

In [25]:
length = 5
n_features = 10
out_index = 2

In [26]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(LSTM(25, input_shape = (length, n_features)))
model.add(Dense(n_features, activation = 'softmax'))
model.compile(loss = 'categorical_crossentropy', optimizer = 'adam', metrics = ['acc'])
print(model.summary())

Using TensorFlow backend.


Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 25)                3600      
_________________________________________________________________
dense_1 (Dense)              (None, 10)                260       
Total params: 3,860
Trainable params: 3,860
Non-trainable params: 0
_________________________________________________________________
None


## Fit the model

In [27]:
for i in range(10000):
    X, y = generate_example(length, n_features, out_index)
    model.fit(X, y, epochs = 1, verbose = 2)

Epoch 1/1
 - 2s - loss: 2.4247 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3708 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2689 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.4050 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2107 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3626 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.4069 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3221 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3967 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3597 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2408 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2670 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2545 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3204 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2818 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.4400 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2249 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2998 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2971 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3213 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.33

Epoch 1/1
 - 0s - loss: 2.2980 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1619 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3248 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3156 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2724 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2451 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.1738 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3155 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3444 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2957 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3071 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2563 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3858 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2442 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3142 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3168 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2639 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1445 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3812 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2065 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2615 - acc: 0.

Epoch 1/1
 - 0s - loss: 2.2125 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2419 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1270 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2048 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8920 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2680 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1865 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1955 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2319 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3450 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2878 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3308 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1416 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1450 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2068 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1449 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3270 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1927 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2002 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2727 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.4241 -

Epoch 1/1
 - 0s - loss: 2.1839 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3442 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0561 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.0208 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.0154 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2477 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.4041 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1442 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0853 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.9036 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.8955 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2371 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0043 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3570 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1266 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2920 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3632 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3326 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0630 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3408 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3884 - acc: 0.0000e+00
Epo

Epoch 1/1
 - 0s - loss: 1.8014 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.9591 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.4872 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8799 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.8614 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3205 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.5329 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.4125 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.7552 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8268 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2039 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3420 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.6853 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2648 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.6934 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.6816 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.9043 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.1784 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2764 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.4647 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8698 - acc: 1.0000
Epoch 1/1
 

 - 0s - loss: 1.3944 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.6803 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0583 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.6242 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.9406 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1718 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.5080 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2110 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3137 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0633 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1100 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1226 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.9190 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.5621 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.6829 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0886 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8185 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.5871 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.8012 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0819 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.5987 - acc: 0.0000e+

Epoch 1/1
 - 0s - loss: 1.0561 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0425 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.4195 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.9890 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1584 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.6627 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.8393 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.6067 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1793 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3538 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1899 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 3.0446 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8419 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3450 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2814 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3329 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.2586 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2521 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.4502 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.9280 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.6829 - acc: 0.0000e+00
Epo

Epoch 1/1
 - 0s - loss: 2.3547 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2161 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.2693 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.9196 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7144 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.9396 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1519 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.3586 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0217 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.9908 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.2650 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3795 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.8460 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0241 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0579 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.7770 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.5594 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.8796 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.8490 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4478 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.0468 - acc: 0.0000e+00

 - 0s - loss: 1.0432 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.1279 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.5068 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.4631 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6125 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7293 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9735 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.5215 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 3.2117 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.6442 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.5719 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.3882 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.4320 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0704 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.8609 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.5108 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.2906 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.9472 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.2550 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7733 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.5861 - acc: 0.0000e+00
Epoch 1/1
 - 0s -

Epoch 1/1
 - 0s - loss: 2.3251 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0202 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4024 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.6980 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 3.5294 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0747 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2063 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4615 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.5225 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.1494 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0318 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3273 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.1186 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0016 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.4369 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2018 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5798 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.1933 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.1979 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1785 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0481 - acc: 0.0000e+00
Epoch 1/1
 - 0s - l

Epoch 1/1
 - 0s - loss: 1.0163 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.5676 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.5329 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2202 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0555 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.5344 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0322 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3996 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2662 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.1013 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1096 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0399 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9673 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.5006 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7357 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.8184 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.1646 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3794 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.1061 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4821 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.9287 - acc: 0.0000e+00
Epoch 1/1
 

 - 0s - loss: 1.8584 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4420 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.8335 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.1282 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.4116 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7498 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.1876 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.5511 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7835 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.4276 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.2724 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.0870 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.7758 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8834 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1641 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1455 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4645 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.9323 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.6131 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7890 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3496 - acc: 0.0000e+00
Epoch 1/1
 - 0s -

Epoch 1/1
 - 0s - loss: 0.7331 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6388 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7875 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3003 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.9231 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.2195 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.4364 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0007 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0416 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1904 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4480 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2636 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0244 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3260 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.5894 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8256 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3369 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0717 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7713 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1762 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.8049 - acc: 0.0000e+00
Epoch 1/1
 - 0s - l

Epoch 1/1
 - 0s - loss: 1.6325 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.5907 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8047 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0167 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.1213 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0171 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.0437 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8119 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.4554 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3381 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7200 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3356 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.7172 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.3027 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.9962 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0417 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2821 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.5980 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.6696 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9849 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.9495 - acc: 0.0000e+00
Epo

Epoch 1/1
 - 0s - loss: 0.8992 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0783 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5329 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.8036 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8752 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2958 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.8086 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8089 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1724 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3286 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1486 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.5049 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.4249 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1311 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1211 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.6278 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.1407 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7004 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3611 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.8357 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.2497 - acc: 0.0000e+00
Epoch 1/1
 - 0s

 - 0s - loss: 0.7630 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.7359 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7066 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3130 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1277 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9610 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.3121 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.3650 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.4418 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.9558 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.4091 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.0950 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2639 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4934 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4413 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.9288 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.3662 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.3468 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7830 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5337 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.1088 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.9685 - 

Epoch 1/1
 - 0s - loss: 1.0662 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.0205 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.8772 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7080 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.8982 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.5477 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.5122 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3086 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.2939 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.1648 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4237 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2046 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.7210 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4914 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3645 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.8093 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6162 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1871 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7232 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3891 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.8999 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4

Epoch 1/1
 - 0s - loss: 0.1765 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6010 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5342 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6458 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1718 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.9979 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.9568 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2697 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1508 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9869 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4036 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.8666 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.3434 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1542 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.4427 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.6029 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2373 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.5955 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4173 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.4856 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.3568 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5

Epoch 1/1
 - 0s - loss: 0.1761 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3475 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1548 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4925 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 3.0137 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8729 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0605 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2763 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.8974 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1498 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.8240 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3156 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.5477 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.1799 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4019 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.4818 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2094 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7751 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6095 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3300 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.8368 - acc: 1.0000
Epoch 1/1
 - 0s - loss:

Epoch 1/1
 - 0s - loss: 0.5094 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.0451 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.9353 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3745 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.3292 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2719 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4281 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1635 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3633 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.6553 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.8493 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5754 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2740 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3120 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.1240 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0772 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1420 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3271 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.6712 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0567 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3167 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2

Epoch 1/1
 - 0s - loss: 1.6387 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.6936 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.9370 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1068 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7288 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5062 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4412 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7453 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4657 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9617 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.5455 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0708 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5240 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6038 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2389 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.8486 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7785 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.6662 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4316 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0175 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.1108 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1

Epoch 1/1
 - 0s - loss: 1.4864 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.1450 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0130 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1417 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0566 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0687 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5479 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2290 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2248 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0641 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7074 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.8597 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3429 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4842 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3394 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1361 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3758 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1271 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.7775 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.8114 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.4708 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7581 - ac

Epoch 1/1
 - 0s - loss: 0.2528 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1316 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1847 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4191 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.8490 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9045 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3653 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0240 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0543 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.7684 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.5753 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.1289 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2452 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0660 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1153 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0060 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.3247 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.6527 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0864 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9375 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0884 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1140 - ac

Epoch 1/1
 - 0s - loss: 2.3695 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0904 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1750 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9992 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.3575 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2088 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.5856 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 2.7525 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.5384 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.9737 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.6902 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.9503 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 3.1848 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4499 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5004 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3734 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.8111 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.5219 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4020 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1145 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.9408 - acc: 0.0000e+00
Epo

Epoch 1/1
 - 0s - loss: 1.1798 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2572 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3307 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3375 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7530 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7904 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.4454 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.3138 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2486 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0190 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4158 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7087 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0197 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7298 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3962 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.8991 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4398 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1099 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.0187 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0718 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0769 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3651 - acc: 1.000

Epoch 1/1
 - 0s - loss: 0.0874 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4169 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1682 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.7119 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.5181 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2808 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.8496 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.2588 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4958 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2493 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3398 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7994 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2059 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0634 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.5432 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0881 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2546 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.5588 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0355 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5340 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3733 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4298 

Epoch 1/1
 - 0s - loss: 1.2214 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0032 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7332 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6598 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2040 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3389 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9778 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.5456 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0662 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.7212 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4465 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2068 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9688 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.9323 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0784 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7526 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1580 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7696 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5623 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6897 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5501 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3542 - ac

 - 0s - loss: 1.0617 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3121 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1634 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1792 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.1111 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.3467 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6895 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1763 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5946 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1254 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.3068 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1746 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7325 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4909 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3591 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.7025 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0976 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0748 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.5894 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2135 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.0708 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.5142 - acc:

Epoch 1/1
 - 0s - loss: 0.0344 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6622 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1643 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5754 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5286 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0339 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5056 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1097 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5097 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0142 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.8534 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1444 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.5833 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5833 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3155 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9966 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0716 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.8306 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.9671 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.5007 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2921 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1282 - acc: 1.000

Epoch 1/1
 - 0s - loss: 0.1360 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1564 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.0546 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.6703 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2275 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2671 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3536 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7640 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4830 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6738 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 3.0568 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7279 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.8977 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.4237 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4811 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9000 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9620 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1519 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3293 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2100 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5817 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6895 - ac

Epoch 1/1
 - 0s - loss: 0.8051 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.4272 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0405 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4503 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7842 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7200 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0366 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3364 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1205 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 3.0604 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1181 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9522 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0225 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0588 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.6727 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0211 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7684 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5084 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3026 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.5726 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0665 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2172 

Epoch 1/1
 - 0s - loss: 1.1888 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0152 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4806 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0408 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4679 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4280 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7591 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.3364 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6273 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2039 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0229 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7238 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5807 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3829 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0447 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3399 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7171 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.5353 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4018 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1773 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4930 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3352 - acc: 1.0000
Ep

Epoch 1/1
 - 0s - loss: 0.0624 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6630 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9127 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.1737 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.1562 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1095 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9603 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.5088 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0404 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7271 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3588 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3683 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4567 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1304 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1546 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0341 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4944 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4488 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0505 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3216 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2097 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2986 - ac

 - 0s - loss: 0.6622 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1177 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4200 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1660 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.5432 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0437 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1140 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1820 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1193 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5668 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6183 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2651 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3213 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2282 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0154 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.9969 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6793 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1327 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5074 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2996 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9633 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2224 - acc: 1.0000
Epoch 1/

Epoch 1/1
 - 0s - loss: 1.1278 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1942 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0840 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4753 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0425 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2001 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1938 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2404 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0178 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0864 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7335 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6539 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1115 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1630 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0185 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0691 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7806 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7131 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9922 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1056 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9334 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2773 - ac

Epoch 1/1
 - 0s - loss: 0.0313 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2279 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 3.2718 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.2289 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.5765 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0280 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0222 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4065 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1908 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3522 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6911 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0197 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0558 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0439 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6924 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2813 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2246 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.5703 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.6295 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0053 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6012 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3028 - acc: 1

Epoch 1/1
 - 0s - loss: 0.4339 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1928 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2278 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3702 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9813 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3801 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2240 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0517 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6839 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3962 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0800 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6582 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0909 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1797 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1080 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2407 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7073 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0336 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1975 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.7713 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0082 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3657 - acc: 1.0000
Ep

 - 0s - loss: 0.1896 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0139 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4011 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9289 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4342 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0130 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9212 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2219 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0313 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3811 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0491 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3413 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6867 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0303 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5785 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6613 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4270 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0210 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0096 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1252 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6054 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1898 - acc: 1.0000
Epoch 1/

Epoch 1/1
 - 0s - loss: 0.3349 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.4113 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0669 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.4906 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4834 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2589 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4409 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3242 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0333 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2408 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1802 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4751 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0139 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7989 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6185 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3458 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1864 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3477 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1030 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5161 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3823 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3301 - acc: 1.0000
Ep

Epoch 1/1
 - 0s - loss: 0.1560 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0880 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.4748 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.8719 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.0177 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.9225 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.7739 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0225 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5200 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2677 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1816 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0713 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6307 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4582 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3743 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1031 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2658 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0503 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0061 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2291 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6856 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1960 - ac

Epoch 1/1
 - 0s - loss: 0.1193 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0166 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1046 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2974 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0769 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0306 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0512 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0122 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1843 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.9129 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0738 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2758 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0641 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0540 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0090 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.3236 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4155 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3710 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0438 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3602 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.4277 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.5547 - acc: 0

Epoch 1/1
 - 0s - loss: 0.0188 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0299 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0751 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0368 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3904 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.6327 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 1.6092 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0559 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1429 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0142 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1348 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.8844 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.8070 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4545 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5832 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0067 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0780 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3030 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2257 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 2.4858 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1318 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2302 - ac

Epoch 1/1
 - 0s - loss: 0.2486 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2747 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1926 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0397 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1634 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2336 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0583 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0734 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1672 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1080 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2462 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0704 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1415 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4737 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1592 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0864 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0658 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2002 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1975 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0541 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1095 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0577 - acc: 1.0000
Epoch 

Epoch 1/1
 - 0s - loss: 0.2744 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4234 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0240 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3575 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1457 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0756 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.2196 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.2086 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0208 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2967 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0624 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0046 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2384 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1404 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0084 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0076 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2329 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1338 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0210 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2541 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0237 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3514 - acc: 1.0000
Epoch 

Epoch 1/1
 - 0s - loss: 1.2218 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0727 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0141 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0383 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1614 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0141 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2168 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3237 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0289 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0070 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0943 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5185 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1892 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0397 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3270 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5302 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0422 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0862 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0800 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1381 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2822 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0381 - acc: 1.0000
Epoch 

Epoch 1/1
 - 0s - loss: 0.0713 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2768 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0465 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0450 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0035 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4012 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0048 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0723 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1478 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1880 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0589 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0134 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0491 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2099 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.1250 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1408 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1214 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4977 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2209 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.8328 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.1178 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5470 - acc: 1.000

Epoch 1/1
 - 0s - loss: 0.1188 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0549 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3658 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0302 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0608 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1785 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3855 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1790 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.7689 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0482 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0122 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.4238 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0027 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0415 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1840 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1202 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0464 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0683 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0068 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1872 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0974 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0765 - acc: 1.0000
Ep

Epoch 1/1
 - 0s - loss: 0.0320 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0538 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0515 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0344 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0567 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2494 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0195 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4921 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1658 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1299 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1144 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1244 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1408 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0796 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2395 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0060 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0141 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0047 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1864 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0685 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1710 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0976 - acc: 1.0000
Epoch 1/1


Epoch 1/1
 - 0s - loss: 0.0809 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2534 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1187 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0192 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0238 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2149 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1306 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0754 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0291 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1882 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0166 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0505 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0248 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0213 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0094 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0426 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2234 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1704 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3730 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0357 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0961 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0799 - acc: 1.0000
Epoch 1/1


Epoch 1/1
 - 0s - loss: 0.0144 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.3625 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0641 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0411 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1480 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1292 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2540 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1061 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0658 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1256 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2237 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1139 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1956 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0762 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0521 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0931 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0485 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0273 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0061 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0450 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0236 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0250 - acc: 1.0000
Epoch 

Epoch 1/1
 - 0s - loss: 0.1617 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2159 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1854 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0189 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0399 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0163 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0400 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1582 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0587 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2731 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1330 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0660 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2601 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0048 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0281 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0660 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0097 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0201 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0038 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2348 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1554 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1045 - acc: 1.0000
Epoch 1/1


Epoch 1/1
 - 0s - loss: 0.1322 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0364 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0101 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0596 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0730 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0043 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0157 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0112 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2986 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0085 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.5800 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0305 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0829 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0247 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.3032 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 1.0906 - acc: 0.0000e+00
Epoch 1/1
 - 0s - loss: 0.0765 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0788 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2235 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1128 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0542 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1178 - acc: 1.0000
Epoch 

Epoch 1/1
 - 0s - loss: 0.0039 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0592 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0051 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0322 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0743 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0400 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1653 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1140 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0437 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2036 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0301 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0246 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2044 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1107 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0160 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0189 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0031 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0277 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0984 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0666 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0050 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0680 - acc: 1.0000
Epoch 1/1


Epoch 1/1
 - 0s - loss: 0.1973 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.4151 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.6056 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0255 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0523 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0734 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0056 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0381 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0106 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0105 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0487 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0309 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0430 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0272 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2709 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0639 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0165 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0855 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0019 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0039 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0285 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0336 - acc: 1.0000
Epoch 1/1


Epoch 1/1
 - 0s - loss: 0.0171 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0057 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0515 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0411 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0010 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0172 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0043 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0450 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0088 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0257 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0160 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0307 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0021 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0221 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0567 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0135 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0304 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0300 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1172 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0086 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0467 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0415 - acc: 1.0000
Epoch 1/1


Epoch 1/1
 - 0s - loss: 0.0244 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2280 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0233 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0012 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0011 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0222 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0898 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0268 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1434 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0649 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0027 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0562 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0469 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0083 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0355 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0111 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0395 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0151 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0239 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0280 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0304 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0029 - acc: 1.0000
Epoch 1/1


Epoch 1/1
 - 0s - loss: 0.0181 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0194 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.2111 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0717 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0052 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0124 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0313 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0142 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0169 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0240 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0438 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0593 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0788 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0799 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1252 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0177 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0562 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1921 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0244 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0145 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.0099 - acc: 1.0000
Epoch 1/1
 - 0s - loss: 0.1452 - acc: 1.0000
Epoch 1/1


## Evaluate model

In [30]:
correct = 0
for i in range(100):
    X, y = generate_example(length, n_features, out_index)
    yhat = model.predict(X)
    if one_hot_decode(yhat) == one_hot_decode(y):
        correct += 1
print('Accuracy: {}'.format((correct / 100.) * 100.))

Accuracy: 100.0


In [34]:
for _ in range(5):
    X, y = generate_example(length, n_features, out_index)
    print(X, y)

[[[0 0 0 0 0 0 0 0 0 1]
  [1 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 1 0 0]
  [1 0 0 0 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0]]] [[0 0 0 0 0 0 0 1 0 0]]
[[[0 0 0 0 0 0 0 1 0 0]
  [1 0 0 0 0 0 0 0 0 0]
  [0 0 1 0 0 0 0 0 0 0]
  [0 0 0 0 0 1 0 0 0 0]
  [0 0 0 0 1 0 0 0 0 0]]] [[0 0 1 0 0 0 0 0 0 0]]
[[[0 1 0 0 0 0 0 0 0 0]
  [0 0 0 1 0 0 0 0 0 0]
  [0 1 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 0 1 0 0]
  [0 1 0 0 0 0 0 0 0 0]]] [[0 1 0 0 0 0 0 0 0 0]]
[[[0 0 0 0 0 1 0 0 0 0]
  [0 0 0 0 1 0 0 0 0 0]
  [0 0 0 0 0 0 1 0 0 0]
  [0 0 0 0 0 0 1 0 0 0]
  [0 0 0 0 0 0 0 0 1 0]]] [[0 0 0 0 0 0 1 0 0 0]]
[[[0 1 0 0 0 0 0 0 0 0]
  [1 0 0 0 0 0 0 0 0 0]
  [0 0 0 0 0 0 1 0 0 0]
  [0 0 0 0 0 1 0 0 0 0]
  [0 0 1 0 0 0 0 0 0 0]]] [[0 0 0 0 0 0 1 0 0 0]]


## Predict

In [35]:
X, y = generate_example(length, n_features, out_index)
yhat = model.predict(X)
print('Sequence {}'.format([one_hot_decode(x) for x in X]))
print('Expected {}'.format(one_hot_decode(y)))
print('Predicted {}'.format(one_hot_decode(yhat)))

Sequence [[2, 2, 4, 5, 0]]
Expected [4]
Predicted [4]
